### ISSUE TITLE
"resolve" option sometimes doesn't work

### ISSUE THREAD

**Issue by tktcorporation** [tkt-actions/add-issue-links#65]
# Overview
-"resolve" option sometimes doesn't work
ref: https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue

# Bugs

## Error Messages

# Checks
- [ ] Documents
- [ ] Implementations
- [ ] Tests

**Comment by tktcorporation** [comment]
Sometimes it works, but sometimes it doesn't.

**Comment by tktcorporation** [comment]
I don't know why.

**Comment by tktcorporation** [comment]
![image](https://user-images.githubusercontent.com/37575408/109373729-fbb10300-78f3-11eb-9e1f-b6dc9ce3bb94.png)

**Comment by MorookaKotaro** [comment]
@tktcorporation 
Should be `Resolve"s"` or `Resolve"d"`. Not `Resolve`👍
