### ISSUE TITLE
Empty description changed to null

### ISSUE THREAD

**Issue by t92549** [tkt-actions/add-issue-links#75]
# Overview
- When an empty description is provided for a PR, this action updates the description to add "Resolve..." etc., but it also adds the word "null" before.

# Bugs
`null` is added to empty descriptions

## Error Messages
No error messages, but see example: https://github.com/gchq/gaffer-doc/pull/228
<img width="648" alt="image" src="https://user-images.githubusercontent.com/80890692/128244850-18047a3d-19a9-49b6-a127-c3f6d245cc56.png">

# Checks
- [ ] Documents
- [x] Implementations
- [x] Tests

**Comment by tktcorporation** [comment]
@t92549 
Sorry, I just realized that you created this issue. I'll check it right away!

**Comment by t92549** [comment]
@tktcorporation Looks great, will update soon

**Comment by t92549** [comment]
@tktcorporation Works great - thanks a lot 🥇

**Comment by tktcorporation** [comment]
@t92549 
Thank you for your report, too!
And, sorry for the late response 🙇
