### ISSUE TITLE
add  branch suffix to finding a related issue

### ISSUE THREAD

**Issue by various999stars** [tkt-actions/add-issue-links#92]
# Overview
- add  branch suffix to finding a related issue.

# Changes
- before: if branch name is `92.issue`, workflow doesn't work.
- after: if branch name is `92.issue`, create link to 92.

# Checks
- [ ] Documents
- [ ] Implementations
- [ ] Tests

**Comment by various999stars** [comment]
I hope you doesn't mind if I create PR for this issue...

**Comment by tktcorporation** [comment]
@various999stars 
Thank you! Please let me know if you have any questions.
(ありがとうございます！なにか不明点あればお気軽に質問いただければと思います:bow:)

**Comment by tktcorporation** [comment]
@various999stars 
https://github.com/tkt-actions/add-issue-links/pull/95#issuecomment-1042914467
It can get the issue number in this format(`92.hoge`) with no changes.
Let me know from which format you want to get an issue number!

**Comment by tktcorporation** [comment]
@various999stars
Thank you for your contributes!
Please feel free to add an issue if you have any inquiry!
